### ISSUE TITLE
Subtasks based on dialog datasets

### ISSUE THREAD

**Issue by kushalchawla** [allenai/natural-instructions#160]
Hi. Are the sub-tasks created from a dialogue dataset in the scope of this project? For instance, utterance-level or dialogue-level classification tasks with natural instructions? I cannot find any other tasks created in this way. Can you share an example?

I would like to add our recent work at NAACL 2021 (https://aclanthology.org/2021.naacl-main.254.pdf). Our dataset contains negotiation dialogues between two participants (MTurkers) and associated strategy annotations.

Potential sub-tasks can include predicting the negotiation strategy used by participants from a given utterance (and some context) and predicting participant satisfaction given a complete dialogue.

Let me know! I would be happy to work towards including these subtasks for this project.

**Comment by danyaljj** [comment]
As long as the tasks is well-defined for many average English speakers, we're happy with it.

**Comment by kushalchawla** [comment]
Sounds good. Thanks. I will get to work.
