### ISSUE TITLE
ATOMIC

### ISSUE THREAD

**Issue by danyaljj** [allenai/natural-instructions#217]
One can create tasks based on the atomic data, where the task definitions define the edges/relations in their dataset:
https://allenai.org/data/atomic-2020

**Comment by swarooprm** [comment]
This one is huge and has a lot of varieties, many tasks can be done using this. Same is true for Conceptnet.

**Comment by yeganehkordi** [comment]
I looked at this dataset. I thought of defining the edges/relations task and several classification tasks based on the meaning (Physical-Entity Commonsense, Social-Interaction Commonsense, and Event-Centered Commonsense) and the relations. I might be able to define 27 tasks based on this dataset. How many tasks and which tasks are desirable?

**Comment by swarooprm** [comment]
You are right! Different relations produce different tasks.
Re: How many tasks: No such estimate, more the better :)

**Comment by ashok-arjun** [comment]
@yeganehkordi If you're still working on this and need help, I can collaborate and take up some tasks

**Comment by yeganehkordi** [comment]
@ashok-arjun Thanks! I haven't started working on the classification tasks based on the meaning (Physical-Entity Commonsense, Social-Interaction Commonsense, and Event-Centered Commonsense). Feel free to take them.

**Comment by ashok-arjun** [comment]
Can you explain what you mean by classification tasks? @yeganehkordi Because all I see in the dataset are such tasks? 

Does this also mean you've also worked on some tasks from the dataset?

**Comment by ashok-arjun** [comment]
@swarooprm @danyaljj Would physical entity tasks be defined in the following way be acceptable? I'm not sure since the input isn't a sentence

**Task**: Predict what the entity is made up of 

**Input**: Bread
**Output**: Dough, wheat

**Comment by danyaljj** [comment]
> @swarooprm @danyaljj Would physical entity tasks be defined in the following way be acceptable? I'm not sure since the input isn't a sentence
> 
> **Task**: Predict what the entity is made up of
> 
> **Input**: Bread **Output**: Dough, wheat

Yeah I think that should be good!

**Comment by danyaljj** [comment]
Just have this in mind that: small high-quality data is better than large low-quality data.

**Comment by ashok-arjun** [comment]
Sure - I'll hand-pick about 15-20 required tasks and work on them.

**Comment by yeganehkordi** [comment]
> Can you explain what you mean by classification tasks? @yeganehkordi Because all I see in the dataset are such tasks?
> 
> Does this also mean you've also worked on some tasks from the dataset?

Yes, I created binary classification tasks based on the relations. For example: determine if given sentences have oEffect relation. 
Also, I have created one task that, given the edges, asks the relation between them.
Besides them, you can create classification tasks based on the meaning. For example, if two edges have a Social-Interaction Commonsense relation or not.

**Comment by danyaljj** [comment]
> Yes, I created binary classification tasks based on the relations. For example: determine if given sentences have oEffect relation. 

Are these tasks merged in? Don't remember seeing them ...

**Comment by yeganehkordi** [comment]
> Are these tasks merged in? Don't remember seeing them ...

No, Actually I was a bit busy. I'll create a pull request soon.

**Comment by danyaljj** [comment]
Got it, take your time!

**Comment by ashok-arjun** [comment]
> > Are these tasks merged in? Don't remember seeing them ...
> 
> No, Actually I was a bit busy. I'll create a pull request soon.

@yeganehkordi  I just finished working on +ve and -ve examples and instances for about 20 tasks of this manner. Could you please let me open the PR instead?

**Comment by yeganehkordi** [comment]
Well, I don't know exactly what to do in this case. @danyaljj Is it okay if we keep both tasks? I guess we had the same problem with stereoset tasks before.

**Comment by danyaljj** [comment]
I am not quite sure. Send whatever PRs you have. We'll resolve the issue based on the PR content.
