### ISSUE TITLE
Analogical reasoning

### ISSUE THREAD

**Issue by ashok-arjun** [allenai/natural-instructions#362]
I'd like to know if analogical reasoning tasks in this format will be accepted:

```
input: "cut : knife. cook : ?"
output: "stove"
```

These are valid tasks and would be beneficial, but I'm not sure of the format. Please help @swarooprm @danyaljj

**Comment by swarooprm** [comment]
Yes, you are encouraged to create such tasks. We don't have such tasks in our repo. Please add @ashok-arjun
