### ISSUE TITLE
Task512 source dataset

### ISSUE THREAD

**Issue by swarooprm** [allenai/natural-instructions#365]
I did not find the source dataset in the paper https://aclanthology.org/D18-1404.pdf mentioned as source in task512 (https://github.com/allenai/natural-instructions-expansion/blob/master/tasks/task512_twitter_emotion_classification.json)

Can you point me to the github location you used to download the dataset?
@gkaramanolakis

**Comment by gkaramanolakis** [comment]
The paper describes the pre-processing procedure of the dataset that I found here: https://huggingface.co/datasets/emotion. Here is more info: https://github.com/huggingface/datasets/blob/master/datasets/emotion/README.md

**Comment by swarooprm** [comment]
Thanks!
