### ISSUE TITLE
Task 171-175 source dataset

### ISSUE THREAD

**Issue by swarooprm** [allenai/natural-instructions#366]
@Mehrad0711, can you point me to the location where I can find the source datasets used in task 171-175.
I am not sure of its exact location in https://github.com/stanford-oval/SPL

**Comment by Mehrad0711** [comment]
Hi @swarooprm,
Instructions to download the dataset (and pretrained models) are under "Pretrained models and datasets" header in that repo.
Alternatively, you can download the restaurants dataset from which those tasks are created from [this link](
https://almond-static.stanford.edu/research/SPL/dataset/restaurants.tar.gz)
Hope this helps.

**Comment by swarooprm** [comment]
Thanks!

**Comment by PhaniRohithaKaza** [comment]
@Mehrad0711 
Hello Mehrad,
I have accessed the dataset but there are no translations in that dataset folders. For example, I'm attaching a screenshot of the data. Could you please tell me how I should proceed?

<img width="907" alt="Datasetamb2" src="https://user-images.githubusercontent.com/42972743/139523494-a7fc6e01-5f33-4c87-adb6-bfdba1706697.png">
<img width="944" alt="DatasetAmbiguity" src="https://user-images.githubusercontent.com/42972743/139523495-ecbcfe2a-9754-444f-8462-2e8dee37f284.png">

**Comment by Mehrad0711** [comment]
Hi @PhaniRohithaKaza,
The dataset folder contains one directory per language. The SPL dataset is a semantic parsing dataset. Each file is monolingual and contains example ids, utterances, and formal annotation. The eval sets are parallel meaning each example is repeated across all different languages (Examples in this repo are constructed only from human translated portion of eval set to ensure high quality.) Please refer to https://github.com/stanford-oval/SPL#pretrained-models-and-datasets for more info.
