### ISSUE TITLE
Repeated instances found in the tasks 

### ISSUE THREAD

**Issue by danyaljj** [allenai/natural-instructions#39]
* @kurbster Looks task 77 merged in  #15 has some repeated instances. For example, check the following input which appears twice: 
```
Step 1: For each row in Movie table, find the corresponding rows in Rating table.
Step 2: find each value of director in the results of step 1 along with the minimum stars of the corresponding rows to each value
```
Note that the two outputs corresponding to this input are different. Assuming that both these outputs are valid outputs, you'd need to group them to form one single instance (one input and two distinct valid outputs). 

Please send a PR with the fix.

**Comment by danyaljj** [comment]
@shailaja183 your task also has repeated instances. 

Check for `Passage: Sandra journeyed to the bathroom. Daniel moved to the garden. Question: Where is Daniel?` in the following task:  `task083_babi_t1_single_supporting_fact_answer_generation`

**Comment by danyaljj** [comment]
@kurbster also see the following repeated line: 
```
 {'input': '[14, -18]', 'output': ['[13, -20]']}
```
in
`task096_conala_list_index_subtraction.json`

**Comment by danyaljj** [comment]
@shailaja183 Also see 
```
 {'input': 'Passage: Fact 1- John went to the kitchen. Fact 2- John went to the hallway. Question: Where is John? Answer: hallway', 'output': ['Fact 2']}
```
in: `task084_babi_t1_single_supporting_fact_identify_relevant_fact.json`

**Comment by danyaljj** [comment]
@kurbster See
```
 {'input': '[0, 2, 4, 4, 1, 5]', 'output': ['[0, 2, 1, 5]']}
```
in `task097_conala_remove_duplicates.json`

**Comment by danyaljj** [comment]
@kurbster and 
```
 {'input': "['H', 'T']", 'output': ['HT']}
```
in 
```
task079_conala_concat_strings.json
```

**Comment by danyaljj** [comment]
@shailaja183 

```
 {'input': 'Passage: John went to the kitchen. John went to the hallway.', 'output': ['Where is John?']}
```
in
```
task082_babi_t1_single_supporting_fact_question_generation.json
```

**Comment by danyaljj** [comment]
@shailaja183 @kurbster just checking if you have seen my earlier comments.

**Comment by swarooprm** [comment]
@kurbster , also when you fix these rename task075 to the latest task number (107 at this point), task075 is repeated with another submitted task

**Comment by shailaja183** [comment]
I have fixed babi tasks regarding repetition of instances. Let me know if the issue persists on my end. 
New commit: repeat instances fix - fa802e9

**Comment by danyaljj** [comment]
@shailaja183 you gotta put that commit on a branch and send a PR (so that we can merge it with our main branch).

**Comment by kurbster** [comment]
Yes, I fixed the errors and made a python script to check for repetitions. I will make a PR.

**Comment by danyaljj** [comment]
Thank you all!
