### ISSUE TITLE
Why input language must be str and not list? 

### ISSUE THREAD

**Issue by Palipoor** [allenai/natural-instructions#430]
Hi!
I thought the tasks in the master branch have the correct format for Input/Output languages, but I saw this in the tests which fails:
``` 
           assert type(data['Input_language']) == list, f'Input_language must be a str.'
            assert type(data['Output_language']) == list, f'Output_language must be a str.'
            assert type(data['Instruction_language']) == list, f'Output_language must be a str.'
```  

Has the format changed?

**Comment by danyaljj** [comment]
Yeah, the format has changed a bit. It's a list of language names to accommodate those tasks that are mixture of multiple languages.

**Comment by danyaljj** [comment]
And that `str` is a typo. Should be `list`.

**Comment by Palipoor** [comment]
Thanks.
