### ISSUE TITLE
Two tasks numbered 119!

### ISSUE THREAD

**Issue by Palipoor** [allenai/natural-instructions#452]
Hi!
For some reason we have two tasks numbered 119.

**Comment by eshaanpathak** [comment]
Yeah, I pointed this out in #224. Daniel said he was going to renumber tasks at the end once everything else is finalized.

**Comment by swarooprm** [comment]
We also have two tasks numbered 868

**Comment by aarunku5** [comment]
There are also two tasks numbered 672

**Comment by pulkitverma25** [comment]
@danyaljj Are we going to renumber all the tasks?
If not, I can simply renumber the repeating task numbers.

**Comment by danyaljj** [comment]
Thanks! We should definitely address these and have a test that prevents repeated numbers.
