### ISSUE TITLE
PR 34 broke the tests 

### ISSUE THREAD

**Issue by danyaljj** [allenai/natural-instructions#46]
@Mihir3009 looks like your PR #34 was not properly tested and our main branch is failing the test. 
Could you check the logs and fix the issue?: 
https://github.com/allenai/natural-instructions-expansion/runs/3149658504

**Comment by swarooprm** [comment]
Seems like this is because we did not have a test to check instance repetition when the PR was originally submitted. We added this test later, but since the PR was already approved, it did not get re-tested with the updated tests and so it failing while merging

**Comment by Mihir3009** [comment]
I updated the files. Please check latest pull request for that

**Comment by swarooprm** [comment]
Thanks! The test is now passing the main branch.
