### ISSUE TITLE
Task 201 bug 

### ISSUE THREAD

**Issue by danyaljj** [allenai/natural-instructions#468]
@shailaja183 Looks like all the labels of this task are "2". I suppose it's a bug: 
https://github.com/allenai/natural-instructions-expansion/blob/master/tasks/task201_mnli_neutral_classification.json

FYI @swarooprm: another instance of how human evaluation helped discover a systemic bug :)

**Comment by swarooprm** [comment]
@aarunku5, can you check your code?
