### ISSUE TITLE
Multiple possible outputs for one input

### ISSUE THREAD

**Issue by Palipoor** [allenai/natural-instructions#52]
Hi,
If the "input"s are the same for several data points, but there're several possible outputs, should they be merged into one data point with multiple "output"s?

**Comment by swarooprm** [comment]
yes, concate them as a list in your instances. So it should be a single data point.

**Comment by ashok-arjun** [comment]
By "concatenate", do you mean using **commas**? That is, an instance would be like below ?

```
{
      "input": "THE_INPUT",
      "output": "OUTPUT_1, OUTPUT_2, OUTPUT_3",
       
 }
```

@swarooprm

**Comment by swarooprm** [comment]
The definition will ask to generate a single output.
Positive and Negative examples will be have single output:
{
      "input": "THE_INPUT",
      "output": "OUTPUT_1",
       
 }
Instances:
{
      "input": "THE_INPUT",
      "output": ["OUTPUT_1", "OUTPUT_2", "OUTPUT_3"],
       
 }

Look at task001 which illustrates the same https://raw.githubusercontent.com/allenai/natural-instructions-expansion/master/tasks/task001_quoref_question_generation.json
