### ISSUE TITLE
XCOPA bug 

### ISSUE THREAD

**Issue by danyaljj** [allenai/natural-instructions#522]
@amirrezamirzaei  In `task1179_xcopa_commonsense_cause_effect_th`, everything is mapped to `effect`.

**Comment by amirrezamirzaei** [comment]
yes, I looked at the data it seems that they have been labeled incorrectly in the source [dataset](https://github.com/cambridgeltl/xcopa). I will try to label them correctly myself.

**Comment by danyaljj** [comment]
I see. If it's something that will take more than 30 mins, don't waste your time on it (It might be easier to drop/replace the task.)

**Comment by amirrezamirzaei** [comment]
I think we can close this issue.
