### ISSUE TITLE
task task903_deceptive_opinion_spam_classification bug 

### ISSUE THREAD

**Issue by danyaljj** [allenai/natural-instructions#524]
Introduced in #340 
@meghpatel  All instance labels are `true`.

**Comment by swarooprm** [comment]
Can you address this soon @meghpatel ?

**Comment by pulkitverma25** [comment]
This can be easily fixed by randomly changing the polarity of a few (approx 40-60%) instances in the description and flipping the corresponding answers to False. I can write a script to do it if it is acceptable?? @swarooprm @danyaljj

**Comment by swarooprm** [comment]
Yes, please go ahead @pulkitverma25
