### ISSUE TITLE
Randomization issue in tests

### ISSUE THREAD

**Issue by swarooprm** [allenai/natural-instructions#55]
@nrjvarshney reports that there is possibly some randomization in the testing script. Sometimes an error appears, sometimes it does not. Also, sometimes all test passes in local, but on the repo, the test fails.

**Comment by danyaljj** [comment]
it's due to this line: 
https://github.com/allenai/natural-instructions-expansion/blob/master/src/test_all.py#L58-L59 
You can increase `500` to a larger number to cover more cases.
