### ISSUE TITLE
Task 333 noisy instances 

### ISSUE THREAD

**Issue by danyaljj** [allenai/natural-instructions#576]
@Palipoor: could you elaborate on the following statement? 

> task 333 has lots of noisy instances!

is it the noise in the output labels or the phrasing of the inputs?

**Comment by Palipoor** [comment]
Hi! Sorry for the delay. 
I think the labels are noisy.
For example: (I censored it)
`This bloke is the sort of c**t who's old woman is fucking someone else but says well what can you do?!"`
this is labeled: not hateful.
Or this is labeled hateful:
`Some women find the Harvey kind of harassment and rape to be not that bad and may even encourage it from time to time depending on hormones.`  
This is not hateful, it's just an incorrect generalization. 
Or this:
`Where are white women allies when a black woman is called a whore? https://t.co/pgfwrQfUFK via @blackvoices Where are we going as a society?`  
is labeled hateful.

**Comment by danyaljj** [comment]
@XudongOliverShen any thoughts?

**Comment by XudongOliverShen** [comment]
The task from HateEval dataset is to identify hate speech against only women and immigrants. This explains the first two instances spotted by @Palipoor. The last instance is indeed with an incorrect label.

`This bloke is the sort of c**t who's old woman is fucking someone else but says well what can you do?!"`
not hateful against women or immigrants, but hateful against men
`Some women find the Harvey kind of harassment and rape to be not that bad and may even encourage it from time to time depending on hormones.`
hateful against women
`Where are white women allies when a black woman is called a whore? https://t.co/pgfwrQfUFK via @blackvoices Where are we going as a society?`
I agree this should be non-hateful and will have it removed.

I will take the following actions:
1. update the task definition and explanations
2. do a possibly non-exhaustive quality check
