### ISSUE TITLE
Task 204 improvement 

### ISSUE THREAD

**Issue by danyaljj** [allenai/natural-instructions#577]
Here is one comment that we got from cloud annotators: 

> Need definitions of genres because I don't know what they all mean. **What's slate and oup?** 

I think the worker is right; the definition for some of these niche categories is not quite clear.

**Comment by danyaljj** [comment]
@aarunku5 wondering if you can help with addressing issue?

**Comment by danyaljj** [comment]
@yeganehkordi 's comment on this task: 

> In task 204, based on the paper, genres refer to the source of collecting the premises. I don't think if the classification of the sentences based on the genres is practical. For example, two-sided, telephone conversations that took place in 1990 or 1991 (TELEPHONE) and Collection of two-sided, in-person conversations that took place in the early 2000s (FACE-TO-FACE) are hard to distinguish.

**Comment by yeganehkordi** [comment]
Also, tasks 197 and 198 have the same problem with the genre.

**Comment by RushangKaria** [comment]
@danyaljj i can take this on!

**Comment by danyaljj** [comment]
@RushangKaria checking if there are any updates on this thread?

**Comment by RushangKaria** [comment]
@danyaljj Will put up the PR tomorrow.
