### ISSUE TITLE
Task 471 examples 

### ISSUE THREAD

**Issue by danyaljj** [allenai/natural-instructions#582]
@Palipoor says: 

> Task 471 has very difficult instances, yet the examples are easy. 

@Maitreyapatel what do you think we move some of the instances to examples?

**Comment by RushangKaria** [comment]
@danyaljj i can take this one. However im unable to assign to myself. Could you please assign it to me?

thanks!

**Comment by danyaljj** [comment]
Done, thanks!

**Comment by RushangKaria** [comment]
I've kept the original examples as-is, and instead appended new ones from the instances as suggested.

**Comment by danyaljj** [comment]
Sounds good!
