### ISSUE TITLE
Failing tests in the main branch 

### ISSUE THREAD

**Issue by danyaljj** [allenai/natural-instructions#602]
Looks like I broke the tests in the main branch by prematurely merging the following PR 🤦 
https://github.com/allenai/natural-instructions-expansion/pull/598 

The issue seems to be related to categories/domains. 
@yeganehkordi @ghlai9665 @swarooprm wondering if you can take a look at the issue?

**Comment by yeganehkordi** [comment]
I'll fix this now!
