### ISSUE TITLE
Task 902 + 903 bug 

### ISSUE THREAD

**Issue by danyaljj** [allenai/natural-instructions#610]
All the instances are mapped to "true" labels.

**Comment by Palipoor** [comment]
I think it's only 903. For 902, it's just a matter of shuffle, not labels.

**Comment by pulkitverma25** [comment]
903 was addressed in https://github.com/allenai/natural-instructions-expansion/pull/655

**Comment by danyaljj** [comment]
Should we close this?

**Comment by pulkitverma25** [comment]
Yes, we can close this now.
