### ISSUE TITLE
Potential bug in task202_mnli_contradiction_classification.json

### ISSUE THREAD

**Issue by danyaljj** [allenai/natural-instructions#621]
Task description mentions `Indicate your answer as '1', '2', or '3' corresponding to the choice number of the selected sentence.` 
although all the instance labels are either 1 or 3 (no 2's). 

@aarunku5 I think you have contributed this task. Could you take a look, please?

**Comment by danyaljj** [comment]
Similarly, in `task200_mnli_entailment_classification.json`

**Comment by pulkitverma25** [comment]
One possible solution will be to drop the label "2" from the instructions.
But even after that, the resulting task will be skewed. The number of instances with label "3" is 5 times those of instances with label  "1".

**Comment by Palipoor** [comment]
I will fix this.

**Comment by Palipoor** [comment]
@danyaljj I think we can close this.
