### ISSUE TITLE
Special tokens in task inputs

### ISSUE THREAD

**Issue by Palipoor** [allenai/natural-instructions#622]
I don't know whether this counts as an issue or not, but in some tasks, there are special tokens for blanks or separation, like <sep> or [MASK]. Is this ok? I feel like this might overestimate the performance of models. Maybe we can replace them with normal separation (\n maybe) and blanks ( __ maybe).

**Comment by danyaljj** [comment]
As long as it is human-readable and consistently used in the task (across instances, negative/positive examples), it's fine.

**Comment by danyaljj** [comment]
In some ways, we want the diversity of such separator tokens. If you would be bad if, say, we train a model that have seen only `\n` and it breaks down with a slight change in the separators.
