### ISSUE TITLE
task1148_maximum_ascii_value improvement 

### ISSUE THREAD

**Issue by danyaljj** [allenai/natural-instructions#629]
@Palipoor mentioned that: 
> People didn't know the ascii values and it was difficult for them. 

This is a valid point. The instructions should define what the asci values are for the characters used in the input. 
A subset of this table might be helpful: https://www.cs.cmu.edu/~pattis/15-1XX/common/handouts/ascii.html

**Comment by mishra-sid** [comment]
Hi, I'll take this task.
