### ISSUE TITLE
URLs in tasks 1601 and 1602 don't work (freebase)

### ISSUE THREAD

**Issue by Palipoor** [allenai/natural-instructions#639]
The tasks are based on some given URLs (generate question/ give an answer based on the contents of a web page), but the URLs don't work, as they're all from freebase.com which seems to be shut down.

**Comment by danyaljj** [comment]
Yeah, FreeBase no longer exists. But the URLs are nothing but the name of the concepts which are articulated at the end of each URL. 
So Ia simple transformation like this should do the trick, I think: 

```
url: http://www.freebase.com/view/en/dominic_monaghan  --> concept: Dominic Monaghan  
```

**Comment by Palipoor** [comment]
It makes sense, I will fix it.
