### ISSUE TITLE
Task1412_dart_predicate_identification skew

### ISSUE THREAD

**Issue by yeganehkordi** [allenai/natural-instructions#652]
This task seems to be heavily skewed toward `food`. 
@danyaljj Shall we consider re-sampling or are we going to solve it with down-sampling later?

**Comment by danyaljj** [comment]
It is skewed, but it's not too bad. 
We should fix it, but definitely not a priority.

**Comment by yeganehkordi** [comment]
Thanks! Also, I guess it's not present in the Tasks statistics file because it has more than 15 outputs. Maybe we can consider a higher threshold.

**Comment by danyaljj** [comment]
That's a good observation! We should consider increasing that limit.

**Comment by yeganehkordi** [comment]
We may need to set the limit higher than 45. I've checked this task now. Here is the result:
   📋 classes: ['1880' '1913' '1960' '1965' '1968' '1970' '1975' '1977' '1985' '1992'
 '2.20' '2000' '2002' '2007' '2008' '2009' '2010' '2011' '2013' 'B.P.'
 'CAN' 'GP' 'HR' 'IATA' 'IPA' 'L3' 'MVP' 'N/R' 'NC' 'PF' 'PLACE' 'RF'
 'SCORE' 'SPG' 'SURFACE' 'TDP' 'TFR' 'V2' 'V3' 'V4' 'customer rating'
 'food'] 
   📋 Norm_counts: [3.38409475e-04 3.38409475e-04 3.38409475e-04 3.38409475e-04
 3.38409475e-04 3.38409475e-04 6.76818951e-04 3.38409475e-04
 6.76818951e-04 3.38409475e-04 3.38409475e-04 3.38409475e-04
 3.38409475e-04 6.76818951e-04 6.76818951e-04 1.35363790e-03
 3.38409475e-04 3.38409475e-04 6.76818951e-04 3.38409475e-04
 3.38409475e-04 3.38409475e-04 3.38409475e-04 3.38409475e-04
 3.38409475e-04 6.76818951e-04 1.35363790e-03 3.38409475e-04
 3.38409475e-04 6.76818951e-04 3.38409475e-04 3.38409475e-04
 3.38409475e-04 3.38409475e-04 3.38409475e-04 3.38409475e-04
 3.38409475e-04 3.38409475e-04 3.38409475e-04 3.38409475e-04
 3.72250423e-03 9.78341794e-01] 
   📋 Distribution of classes: [   1    1    1    1    1    1    2    1    2    1    1    1    1    2
    2    4    1    1    2    1    1    1    1    1    1    2    4    1
    1    2    1    1    1    1    1    1    1    1    1    1   11 2891] 
   📊 entropy= 0.04776638885622694

**Comment by danyaljj** [comment]
Oh, that's quite a skew!  Downsampling is not gonna fix it. 

@RushangKaria looks like you have added this task. Do we have more instances that have labels other than `food`?

**Comment by RushangKaria** [comment]
@danyaljj  I'll take a look and update tonight!

**Comment by RushangKaria** [comment]
@danyaljj sorry for the delay! Went on thanksgiving break.

Yes, we can add other instances if needed. Its finals week this week so ill update a bit later.

**Comment by danyaljj** [comment]
Let us know if you can address this in the coming days.

**Comment by RushangKaria** [comment]
@danyaljj yes, ill put up a PR this weekend!

**Comment by RushangKaria** [comment]
Hi @danyaljj

It looks like the "food" label is the only predicate that actually appears in the sentence.
Other sentences in this dataset have different special labels that appear as predicates for which there is no documentation.

I've put up a PR using these special tags however im not sure where to find their definitions.
