### ISSUE TITLE
task697 is incomplete.

### ISSUE THREAD

**Issue by pulkitverma25** [allenai/natural-instructions#661]
For any question on formal logic sentence, vocabulary, universe, and semantics should also be given to validate if the sentence evaluates to true or false. The task assumes an implied mental model of these things. For any statement, I can create a universe, vocabulary, and semantics to make all options true. I think we should remove this task.

**Comment by pulkitverma25** [comment]
E.g.,
```
         {
            "input": "Select the best translation into predicate logic: Abdul and Cleopatra are Egyptian.\n(A)Ea • Ec (B)Ea • c (C)Ae ∨ Ce (D)Ex • Ey",
            "output": [
                "A"
            ]
        },
```
It assumes what E, a, A, c, e, x, and y mean in the options, and chooses a correct answer based on the original authors universe, vocabulary, and the semantics.

**Comment by danyaljj** [comment]
> The task assumes an implied mental model of these things.  

Do you think humans (e.g., crowdworkers) would be able to solve these? 
My rule-of-thumb is, if humans can do it, it's reasonable to expect machines to do it as well.

**Comment by pulkitverma25** [comment]
> > The task assumes an implied mental model of these things.
> 
> Do you think humans (e.g., crowdworkers) would be able to solve these? My rule-of-thumb is, if humans can do it, it's reasonable to expect machines to do it as well.

Some crowd workers might do it. If the bar is simply " if humans can do it, it's reasonable to expect machines to do it as well", then I think we can keep the task as is.

**Comment by Palipoor** [comment]
I am going to second @pulkitverma25's comment. The notation used in the answer choices is weird, and even for someone who knows formal logic, it might need explanation. I guess we can keep it and just increase the number of examples, to cover different operators.

**Comment by danyaljj** [comment]
Sounds fair to me.

**Comment by danyaljj** [comment]
#698 has improved the task with a few examples, bit it is still a bit odd. Closing it, for now, if you see that it can be improved in anyway, let's discuss it.
