### ISSUE TITLE
Some instances in task667 does not make sense.

### ISSUE THREAD

**Issue by pulkitverma25** [allenai/natural-instructions#664]
Many of the instances in task667 does not make sense. They are based on info that is not included in the question.
E.g.:
        {
            "input": "The complexity of the theory.\n(A)1,2,3,4 (B)1,3,4 (C)1,2,3 (D)1,2,4",
            "output": [
                "C"
            ]
        },
        {
            "input": "The Private Sector Social Enterprise Model.\n(A)1,2,4 (B)2,3,4 (C)1,2,3,4 (D)1,2,3",
            "output": [
                "D"
            ]
        },

**Comment by pulkitverma25** [comment]
I am planning to remove all such instances from these 2 files.

**Comment by danyaljj** [comment]
hmm ... these instances were like this in the original dataset? Or somehow we messed up in reading the data?

**Comment by pulkitverma25** [comment]
I haven't seen the original dataset, I can check it out.

@sujan242 Can you also have a look at it? Did your script remove some information from the questions by any chance?

**Comment by Sujan242** [comment]
> I haven't seen the original dataset, I can check it out.
> 
> @Sujan242 Can you also have a look at it? Did your script remove some information from the questions by any chance?

These instances are present in the original dataset as well(https://github.com/hendrycks/test). 
![image](https://user-images.githubusercontent.com/48852710/144184217-a630931d-75e5-4e44-a197-621e2dfac506.png)

Let me take this issue up because simply removing these instances might introduce skewness.

**Comment by pulkitverma25** [comment]
> > I haven't seen the original dataset, I can check it out.
> > @Sujan242 Can you also have a look at it? Did your script remove some information from the questions by any chance?
> 
> These instances are present in the original dataset as well(https://github.com/hendrycks/test). ![image](https://user-images.githubusercontent.com/48852710/144184217-a630931d-75e5-4e44-a197-621e2dfac506.png)
> 
> Let me take this issue up because simply removing these instances might introduce skewness.

Check PR#665 once. I don't think there are too many such instances. If you think such instances are low, we need not worry about skewness.

**Comment by Sujan242** [comment]
> Check PR#664 once. I don't think there are too many such instances. If you think such instances are low, we need not worry about skewness.

Thanks! I think we need not worry about skewness since there are fewer than 20 such instances.

**Comment by danyaljj** [comment]
@pulkitverma25 good to close this issue?

**Comment by pulkitverma25** [comment]
Yes. We can close this now.
