### ISSUE TITLE
Task1562_clickbait_new_bg_answer_generation

### ISSUE THREAD

**Issue by yeganehkordi** [allenai/natural-instructions#685]
This task is to generate the fake news score based on the given news.
`Fake-news score is a numeric value indicating whether the given news article is fake or not. The score is a numeric value ranging from 0 to 10.`
I think it can be so hard even for humans to generate this score because we don't have a metric for recognizing the difference between the scores. I saw we don't have feedback on this task, and I guess it's because the task is in Bulgarian.

task1563_clickbait_new_bg_answer_generation has the same problem. 
`You are expected to generate a value for the click-bait score. Click-bait score is a a numeric value indicating whether the given article is click-bait or not. The output can contain only positive numeric values of upto 10 digits in length.`

**Comment by danyaljj** [comment]
Agreed. I am fine if we drop these tasks.
