### ISSUE TITLE
Task1578 and Task288 

### ISSUE THREAD

**Issue by yeganehkordi** [allenai/natural-instructions#686]
These tasks are summarization tasks based on the Gigaword dataset. They are almost the same.

**Comment by Palipoor** [comment]
Task 288 has 6500 instances and task 1578 has almost 1900. Both are probably randomly sampled from Gigaword. Also, task 288 has better explanations. I guess we can keep 288 and drop 1578. 
Also, task 1579 is "incorrect summary generation" and task 289 is verifying whether a summary is correct. I think task 289 makes more sense. An incorrect summary can be anything. 
@danyaljj Should I drop those two?

**Comment by danyaljj** [comment]
Here is a suggestion: 

- I think there is value in having multiple task definitions. In one PR, we can change the `"Definition": ""` field to `"Definition": [""]`. 
- In followup PRs, we can merge the tasks that are equivalent **and** based on the same underlying dataset. 


What do you think?

**Comment by Palipoor** [comment]
It sounds good to me! Although in this particular case what I meant was the explanations for positive and negative examples are better in task 288. Do we have many other duplicate tasks?

**Comment by danyaljj** [comment]
> Do we have many other duplicate tasks? 

I think do, we just haven't found them yet :)   

> Although in this particular case what I meant was the explanations for positive and negative examples are better in task 288. 

I think we're optimizing two objectives: more diversity for our annotations (more examples, more definitions, etc.) while reducing noise and redundancy (fewer duplications, fewer garbage examples, etc.) So, if the examples/explanations are not quite duplicate/noisy (as in, a human can read and be, at least partially, convinced), I'd say let's retain them.

**Comment by danyaljj** [comment]
@Palipoor wondering if you can help with merging these tasks?

**Comment by Palipoor** [comment]
Sure! Will do tomorrow.
