### ISSUE TITLE
The problem with task 839

### ISSUE THREAD

**Issue by Palipoor** [allenai/natural-instructions#706]
Summarizing my comment in #702 : 

Task 839 is based on the CDT dataset. The CDT itself is skewed and contains a lot of non-bullying instances. It seems like this task is constructed from a lot of non-bullying instances, and adding either "Does the tweet contain cyberbullying (harmful) content?" or "Question: Is the tweet free of any cyberbullying (harmful) content?" to them, to artificially make a balanced classification(more like question answering I guess) task. If we are to merge this with task 838 from the same dataset, it'll be skewed, and I don't think the task itself is worth keeping.

**Comment by danyaljj** [comment]
So, in summary, you're suggesting to drop both 839 and 838?

**Comment by Palipoor** [comment]
No, just 839. 838 is balanced now, I downsampled the non-bullying instances.
