### ISSUE TITLE
SCAN dataset

### ISSUE THREAD

**Issue by danyaljj** [allenai/natural-instructions#73]
https://github.com/brendenlake/SCAN

**Comment by eshaanpathak** [comment]
I can take a look at this one. How many tasks should there be? I was thinking 3 with one from the entire dataset, one from tasks_train_length.txt for shorter sequences, and one from tasks_test_length.txt for longer sequences. Let me know what you think!

**Comment by danyaljj** [comment]
Thanks for taking the initiative on this! 🙏 

Sounds reasonable to me. And I think, each of these can be done in two directions: 

- command to action sequence 
- action sequence to the command 


FYI @swarooprm

**Comment by eshaanpathak** [comment]
I like that idea. I'll get started on this. What would the categories be for this? Long Text Generation and Text Modification?

**Comment by danyaljj** [comment]
Cool, thanks! 

I think "action sequence to the command" is more like "Long Text Generation". 

The reverse direction (mapping text to pre-defined steps) is more like "parsing" into formal language. @swarooprm what should be the category in this case?

**Comment by swarooprm** [comment]
Good question! We don't have a well-defined category here. I suggest to have "structured text generation" category for the second task (mapping text to pre-defined steps). 

Note that, we have a similar task where we convert natural language to SQL (https://github.com/allenai/natural-instructions-expansion/blob/master/tasks/task107_splash_question_to_sql.json).

**Comment by swarooprm** [comment]
https://github.com/allenai/natural-instructions-expansion/pull/81 addressed it.
