### ISSUE TITLE
Do you have a plan to release a standard evaluation protocol?

### ISSUE THREAD

**Issue by todpole3** [allenai/natural-instructions#757]
This is an excellent collection of tasks. I wonder if there is a plan to release a standard train/test split or evaluation protocol?
Or is it already released somewhere and I missed it? :) Thanks.

**Comment by danyaljj** [comment]
The short answer is "yes"! 

We are working to consolidate the split and should be able to release something soon -- hopefully in a week or two.

FYI @yizhongw

**Comment by todpole3** [comment]
Thanks for the heads-up!

**Comment by JunShern** [comment]
Hi @danyaljj, thanks for this work! Can I clarify - since this issue was a few weeks ago, and I saw the paper released recently, were you referring to the paper being released or is there something else coming?

In particular, I am looking for
1. The evaluation split of tasks
2. Code to reproduce the results of the paper (e.g. for finetuning and evaluating on this dataset)

If they are not yet released, it would be helpful if you could give a rough idea for when that would be released (I am trying to decide whether to include this excellent benchmark in my own work but that would depend on the timeline).

Thank you!

**Comment by yizhongw** [comment]
> Hi @danyaljj, thanks for this work! Can I clarify - since this issue was a few weeks ago, and I saw the paper released recently, were you referring to the paper being released or is there something else coming?
> 
> In particular, I am looking for
> 
> 1. The evaluation split of tasks
> 2. Code to reproduce the results of the paper (e.g. for finetuning and evaluating on this dataset)
> 
> If they are not yet released, it would be helpful if you could give a rough idea for when that would be released (I am trying to decide whether to include this excellent benchmark in my own work but that would depend on the timeline).
> 
> Thank you!

Thanks for your interest! We are planning to release the splits and evaluation scripts next week (hopefully by Wed). Does this work for your schedule?

**Comment by JunShern** [comment]
Amazing, yes next week should work for us! Thanks for the quick response and all the best. :)

**Comment by JunShern** [comment]
Hi @yizhongw, any update on this? Sorry to rush you, but for our planning it'll be helpful to know whether we will get to include this or not.

**Comment by yizhongw** [comment]
> Hi @yizhongw, any update on this? Sorry to rush you, but for our planning it'll be helpful to know whether we will get to include this or not.

@JunShern Sorry for being late on this! We have merged this [PR](https://github.com/allenai/natural-instructions/pull/764) just now, and now the official evaluation splits can be found [here](https://github.com/allenai/natural-instructions/tree/master/splits). You can follow the instructions there for setting up your experiments. 
We also released our [code](https://github.com/yizhongw/Tk-Instruct) for Tk-Instruct model and [checkpoints](https://huggingface.co/models?search=tk-instruct-). Feel free to let me know if you find any issue!

**Comment by JunShern** [comment]
Amazing, thank you! I'll be looking into it :)
