### ISSUE TITLE
Task languages

### ISSUE THREAD

**Issue by abrazinskas** [allenai/natural-instructions#772]
Hello everyone,

Could anyone please provide the statistics of task languages? In the paper, it is stated that about 500 of tasks are non-English but no details. I was also not able to find this information in the repository. 

Thanks for advance,
Arthur

**Comment by danyaljj** [comment]
Each task file (in https://github.com/allenai/natural-instructions/tree/master/tasks) contains keys that indicate its languages: 
```
 "Input_language": [""], 
  "Output_language": [""],
  "Instruction_language": [""], 
```
You should be able to write a simple script to collect any statistics that you want. 

FYI @yizhongw
