### ISSUE TITLE
Should we separate it to different tasks for different topics in one dataset?

### ISSUE THREAD

**Issue by liusiyi641** [allenai/natural-instructions#87]
The AFS (argument facet similarity) dataset has argument pairs with similarity scores in three different topics (gun control, death penalty, gay marriage). They are all basically the same task, but the topic they are discussing are different. I was thinking that I should combine them into one argument similarity task, but they provided their data in separate files, and they also separated all of their evaluation results for each topic (see https://arxiv.org/pdf/1709.01887.pdf Table 4). So I wonder if they are concerned of some domain differences and if I should also separate them into three different tasks. Thanks

**Comment by swarooprm** [comment]
Good question! 
Seems like finding similarity scores for various argument pairs require some sort of domain knowledge that is specific to each of the 3 topics (gun control, death penalty, gay marriage). A person having knowledge about gun control may not be able to answer similar questions on death penalty etc. Please have a look at the data and verify if this is true. If this is true, then create 3 different tasks. If this is not true, and annotating similarity across the topics requires some general commonsense knowledge and nothing specific to the individual topics, please create only one task combining all data.
