### ISSUE TITLE
Is the CODAH dataset a good addition?

### ISSUE THREAD

**Issue by eshaanpathak** [allenai/natural-instructions#93]
I'm currently looking at the CODAH dataset that was listed in the spreadsheet (https://github.com/Websail-NU/CODAH). Is this a good addition? The paper states that this dataset was adversarially constructed so GPT-1 and BERT would struggle, but after looking at the dataset, I'm pretty confident that current large SOTA models (GPT-3, T5, RoBERTa, etc.) will crush this. Should I still go ahead and format this json file?

**Comment by swarooprm** [comment]
Yes. We also have its templates collected. 
Regarding GPT3, T5 solving it: we also have SQuAD dataset in our collection. Easier datasets can be used for training,  note that we don't plan to use all datasets for evaluation.
