### ISSUE TITLE
Define an NER task 

### ISSUE THREAD

**Issue by danyaljj** [allenai/natural-instructions#95]
- The task definition would have to define a list of tags (it could be coarse labels, such as `Person, Location`, etc. Or fine-grained like `president, politician, doctor`, etc).
 - each instance can be: what is the semantic type of the mention x in the following sentence: y?
 - there are a couple of datasets out there we can use for this: https://github.com/juand-r/entity-recognition-datasets

**Comment by mishra-sid** [comment]
Hi, I'm working on this task since It's similar in structure to PoS tagging ( for which I recently raised a PR #279) for some datasets commonly used as benchmark for this task ( http://nlpprogress.com/english/named_entity_recognition.html ): 
1. CoNLL
2. GUM-3.1.0
3. wikigold
4. BTC
